// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaClinica.Infrastructure.Context;

#nullable disable

namespace SistemaClinica.Infrastructure.Migrations
{
    [DbContext(typeof(SistemaClinicaDbContext))]
    partial class SistemaClinicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraInclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("SituacaoConsulta")
                        .HasColumnType("integer")
                        .HasComment("Situação da consulta: 1 - Agendada, 2 - Confirmada, 3 - Cancelada, 4 - Finalizada.");

                    b.Property<int?>("UsuarioIdAlteracao")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioIdInclusao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataConsulta");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraInclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UsuarioIdAlteracao")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioIdInclusao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("Especialidades", (string)null);
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraInclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<char>("Situacao")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)")
                        .HasComment("Situação do usuário: A - Ativo, I - Inativo.");

                    b.Property<int?>("UsuarioIdAlteracao")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioIdInclusao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("SistemaClinica.Domain.Entities.Usuario");

                    b.ToTable("Administradores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHoraInclusao = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@clinica.com",
                            Nome = "Administrador",
                            Role = 1,
                            Senha = "PBKDF2$100000$yQrfz4C53E0xBeII0RI26Q==$oIv3/q8P/66pPukotRclELVJ3itU7vVHHXi3ymbVp3o=",
                            Situacao = 'A',
                            UsuarioIdInclusao = 0
                        });
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Medico", b =>
                {
                    b.HasBaseType("SistemaClinica.Domain.Entities.Usuario");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("CRM")
                        .IsUnique();

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Paciente", b =>
                {
                    b.HasBaseType("SistemaClinica.Domain.Entities.Usuario");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Recepcionista", b =>
                {
                    b.HasBaseType("SistemaClinica.Domain.Entities.Usuario");

                    b.ToTable("Recepcionistas", (string)null);
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("SistemaClinica.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Consultas")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaClinica.Domain.Entities.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaClinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Administrador", b =>
                {
                    b.HasOne("SistemaClinica.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("SistemaClinica.Domain.Entities.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Medico", b =>
                {
                    b.HasOne("SistemaClinica.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaClinica.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("SistemaClinica.Domain.Entities.Medico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("SistemaClinica.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("SistemaClinica.Domain.Entities.Paciente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Recepcionista", b =>
                {
                    b.HasOne("SistemaClinica.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("SistemaClinica.Domain.Entities.Recepcionista", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Especialidade", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("SistemaClinica.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
