services:
  postgres:
    image: postgres:16
    container_name: sistema-clinica-postgres
    environment:
      POSTGRES_DB: sistema_clinica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sistema-clinica-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinica.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: